"""Add delivery_address to orders table

Revision ID: 16bb789b3e99
Revises: 
Create Date: 2026-03-20 22:15:11.148492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bb789b3e99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite cannot add NOT NULL column with no default value when table already has rows.
    # Add as nullable first, fill existing records, then keep readonly semantics at application layer.
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=500), nullable=True))
    op.execute("UPDATE orders SET delivery_address = '' WHERE delivery_address IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
